import 'server-only';

/** Canonical demo projects. Matches RAG baseline seed — not the DEV-ONLY mock fixtures. */
export const DEFAULT_PROJECTS = [
  {
    id: 'aurora',
    name: 'ExpenseTracker',
    codeName: 'PROJECT AURORA',
    company: 'Aurora Technologies',
    description: 'Expense management & corporate card intelligence platform for fast-scaling SMBs.',
    industry: 'FinTech',
    stage: 'Beta',
    targetUsers: 'SMB Finance Managers & Operations Leads',
    expectedLaunchDate: '2026-10-15',
    health: 'WATCH',
    failureRisk: 0,
    riskTrend: 'Awaiting Analysis',
    predictedNextFailure: 'No Failure Predicted (Awaiting Analysis)',
    predictionConfidence: 0,
    historicalSimilarity: 0,
    privacyLevel: 'PRIVATE',
    sourcesUploaded: [] as string[],
    lastAnalyzedAt: null as string | null,
    activeFailureSeedsCount: 0,
  },
  {
    id: 'pulseflow',
    name: 'PulseFlow CRM',
    codeName: 'PROJECT PULSE',
    company: 'Pulse Health Systems',
    description: 'Patient relationship management and automated clinical trial follow-up telemetry engine.',
    industry: 'HealthTech',
    stage: 'General Availability',
    targetUsers: 'Clinical Research Coordinators & Clinic Admins',
    expectedLaunchDate: '2026-11-30',
    health: 'WATCH',
    failureRisk: 0,
    riskTrend: 'Awaiting Analysis',
    predictedNextFailure: 'No Failure Predicted (Awaiting Analysis)',
    predictionConfidence: 0,
    historicalSimilarity: 0,
    privacyLevel: 'ORGANIZATION',
    sourcesUploaded: ['CUSTOMER_FEEDBACK', 'PRODUCT_METRICS', 'INCIDENT_REPORTS'],
    lastAnalyzedAt: null as string | null,
    activeFailureSeedsCount: 0,
  },
  {
    id: 'zenith',
    name: 'Zenith Checkout',
    codeName: 'PROJECT ZENITH',
    company: 'Zenith Commerce',
    description: 'High-throughput headless checkout infrastructure with sub-second bank rail validation.',
    industry: 'E-Commerce',
    stage: 'Scaling',
    targetUsers: 'Enterprise E-Commerce Engineers',
    expectedLaunchDate: '2027-01-15',
    health: 'WATCH',
    failureRisk: 0,
    riskTrend: 'Awaiting Analysis',
    predictedNextFailure: 'No Failure Predicted (Awaiting Analysis)',
    predictionConfidence: 0,
    historicalSimilarity: 0,
    privacyLevel: 'PUBLIC',
    sourcesUploaded: ['ENGINEERING_METRICS', 'TEAM_OPERATIONS'],
    lastAnalyzedAt: null as string | null,
    activeFailureSeedsCount: 0,
  },
] as const;

export function getDefaultProject(id: string) {
  return DEFAULT_PROJECTS.find((project) => project.id === id) ?? null;
}
